---
title: "LBGFS2022 - Exam: Problem 5: Variance and Inbreeding"
output: html_notebook
---

## Disclaimer
Design of problem on variance and inbreeding. This is copied from the exam of FS2019. 


## Definitions

```{r prob1-prepare,echo=FALSE}
n_exile_year <- 1892
n_export_year <- 2022
n_total_nr_sheep <- 2200
n_nr_subpop <- 4
n_nr_female_per_male <- 10
n_gen_interval <- 1.3
# compute derived quantities
n_total_nr_female <- n_total_nr_sheep / (n_nr_female_per_male + 1) * n_nr_female_per_male
n_total_nr_female_per_subpop <- n_total_nr_female / n_nr_subpop
n_nr_gen <- (n_export_year - n_exile_year) / n_gen_interval
n_delta_F <- 1 / (2 * n_total_nr_female_per_subpop)
n_delta_F
```

Inbreeding

```{r prob1a-sol, echo=FALSE}
n_F_t <- 1 - (1 - n_delta_F)^n_nr_gen
```

Limit

```{r prob1b-prepare, echo=FALSE}
n_F_t_limit <- 0.1
n_nr_gen_limit <- (log(1 - n_F_t_limit))/ (log(1 - n_delta_F))
n_nr_gen_limit_round <- ceiling(n_nr_gen_limit)
n_limit_year <- n_exile_year + n_nr_gen_limit_round * n_gen_interval
n_limit_year_rounded <- ceiling(n_limit_year)
```


Depression

```{r}
n_maf_locus_w <- 0.045
n_homo_geno_val <- 50
n_het_geno_val <- 15
n_inb_depr <- 2 * n_het_geno_val * n_maf_locus_w * (1-n_maf_locus_w) * n_F_t_limit
n_inb_depr_rounded <- round(n_inb_depr, digits = 4)
```

Variance

```{r}
n_add_gen_var_base_pop <- 2 * n_maf_locus_w * (1-n_maf_locus_w) * n_homo_geno_val^2
n_bt_line <- 2*n_F_t_limit * n_add_gen_var_base_pop
n_win_line <- (1-n_F_t_limit) * n_add_gen_var_base_pop
n_add_gen_var <- (1+n_F_t_limit) * n_add_gen_var_base_pop
n_dom_gen_var <- (2 * n_maf_locus_w * (1-n_maf_locus_w) * n_het_geno_val)^2
n_total_var <- (1+n_F_t_limit) * n_add_gen_var_base_pop + n_dom_gen_var
tbl_gen_anova_sol <- tibble::tibble(Source = c("Between lines", "Within lines","Total additive", "Dominance", "Total genetic"),
                                    Variance = c("$2FV_U$", "$(1-F)V_U$", "$(1+F)V_U$", "$V_D$", "$V_G$"),
                                    Values   = round(c(n_bt_line,
                                                 n_win_line,
                                                 n_add_gen_var,
                                                 n_dom_gen_var,
                                                 n_total_var), digits = 2))
```


