---
title: "Additional Material"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Additional Material}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Additional material for the course is shown below.


# Slides

```{r slide-table, echo=FALSE, message=FALSE, warning=FALSE}
root_url <- "https://charlotte-ngs.github.io/lbgfs2022" 
sl_url <- paste0(root_url, "/sl/")
misc_url <- paste0(root_url, "/misc/")
tbl_sl <- tibble::tibble(Nr = c(1, 2, 3, 4, 5, 6, 7, 8),
                         Date = c("2022-09-23",
                                  "2022-09-30",
                                  "2022-10-07",
                                  "2022-10-21",
                                  "2022-10-28",
                                  "2022-11-04",
                                  "2022-11-04",
                                  "2022-11-18"),
                         Topic = c(
                           paste0("[Introduction to Livestock Breeding and Genomics](", 
                                  sl_url, 
                                  "lbgfs2022_slides_l01_intro_lbg.pdf)", 
                                  collapse = ""),
                           paste0("[Basics of Quantitative Genetics](", 
                                  sl_url, 
                                  "lbgfs2022_slides_l02_basics_qg.pdf)", 
                                  collapse = ""),
                           paste0("[Genetic Evaluation](",
                                  sl_url,
                                  "lbgfs2022_l03_gen-eval.pdf)",
                                  collapse = ""),
                           paste0("[BLUP](",
                                   sl_url,
                                   "lbgfs2022_slides_l04_blup.pdf)",
                                   collapse = ""),
                           paste0("[Genetic Covariance between Animals](",
                                  sl_url,
                                  "lbgfs2022_l05_slides_gencov.pdf)",
                                  collapse = ""),
                           paste0("[Numerator Relationship Matrix](",
                                  sl_url,
                                  "lbgfs2021_l06_slides_numrelmat.pdf)",
                                  collapse = ""),
                           paste0("[Inverse Numerator Relationship Matrix](",
                                  sl_url,
                                  "lbgfs2021_l06_slides_invnumrelmat.pdf)",
                                  collapse = ""),
                           paste0("[Variance and Inbreeding](",
                                  sl_url,
                                  "lbgfs2022_l07_slides_var_inb.pdf)",
                                  collapse = "")
                         ))
knitr::kable(tbl_sl)
```                         

# Slides with Notes

```{r sl-with-notes, echo=FALSE, message=FALSE, warning=FALSE}
slwn_url <- paste0(root_url, "/sl_with_notes/")
tbl_slwn <- tibble::tibble(Nr = c(1, 2),
                           Date = c(rep("2022-11-18", 2)),
                           Topic = c(
                             paste0("[Inverse Numerator Relationship Matrix](",
                                  slwn_url,
                                  "lbgfs2021_l06_slides_invnumrelmat_with_notes.pdf)",
                                  collapse = ""),
                             paste0("[Variance and Inbreeding](",
                                    slwn_url,
                                    "lbgfs2022_l07_slides_var_inb_with_notes.pdf)",
                                    collapse = "")
                             ))
knitr::kable(tbl_slwn)
```


# Videos

```{r video-table, echo=FALSE, message=FALSE, warning=FALSE}
tbl_video <- tibble::tibble(Nr = c(1, 2, 3, 4, 5, 6, 7, 8),
                            Date = c("2022-09-23",
                                     "2022-09-30",
                                     "2022-10-07",
                                     "2022-10-14",
                                     "2022-10-21",
                                     "2022-10-28",
                                     "2022-11-04",
                                     "2022-11-11"),
                            Topic = c(
                              "[Introduction to Livestock Breeding](https://youtu.be/tp09u8Z5lOM)",
                              "[Quantiative Genetics](https://youtu.be/wBj1ZwkMyR4)",
                              "[Single Locus Breeding Values](https://youtu.be/Ie6ozie2aWA)",
                              "[Genetic Evaluation](https://youtu.be/_X-asWKKRgM)",
                              "[Repeated Records and Progeny](https://youtu.be/_oCnakzpsB0)",
                              "[Linear fixed effects models and linear mixed effects models](https://youtu.be/EFtJcn9XvTs)",
                              "[Sire model, animal model and numerator relationship matrix](https://youtu.be/sQvt-ZtYcgk)",
                              "[Numerator relationship matrix, if-statements and loops in R](https://youtu.be/3uKjJWs2IAI)"
                            ))
knitr::kable(tbl_video)
```


## Overhead Picture

```{r, ohp-table, echo=FALSE, message=FALSE, warning=FALSE}
s_ohp_url <- file.path(root_url, "ohp/")
tbl_ohp <- tibble::tibble(Nr = c(1, 2, 3, 4, 5, 6, 7, 8),
                          Date = c("2022-09-23",
                                   "2022-09-30",
                                   "2022-10-07",
                                   "2022-10-14",
                                   "2022-10-21",
                                   "2022-10-28",
                                   "2022-11-04",
                                   "2022-11-11"),
                          Topic = c(
                              paste0("[Introduction to Livestock Breeding](", 
                                     s_ohp_url, 
                                     "20220923_ohp_l01.pdf)", 
                                     collapse = ""),
                              paste0("[Quantitative Genetics](", 
                                     s_ohp_url, 
                                     "20220930_ohp_l02.pdf)", 
                                     collapse = ""),
                              paste0("[Single Locus Breeding Values](", 
                                     s_ohp_url, 
                                     "20221007_ohp_l03.pdf)", 
                                     collapse = ""),
                              paste0("[Genetic Evaluation](", 
                                     s_ohp_url, 
                                     "20221014_ohp_l04.pdf)", 
                                     collapse = ""),
                              paste0("[Repeated Records and Progeny](", 
                                     s_ohp_url, 
                                     "20221021_ohp_l05.pdf)", 
                                     collapse = ""),
                              paste0("[Linear fixed effects models and linear mixed effects models](", 
                                     s_ohp_url, 
                                     "20221028_ohp_l06.pdf)", 
                                     collapse = ""),
                              paste0("[Sire model, animal model and numerator relationship matrix](", 
                                     s_ohp_url, 
                                     "20221104_ohp_l07.pdf)", 
                                     collapse = ""),
                              paste0("[Numerator relationship matrix, if-statements and loops in R](",
                                     s_ohp_url,
                                     "20221111_ohp_l08.pdf)",
                                     collapse = "")
                            ))
knitr::kable(tbl_ohp)
```


## Datasets

```{r, data-table, echo=FALSE, message=FALSE, warning=FALSE}
s_data_url <- file.path(root_url, "data/")
tbl_data <- tibble::tibble(Nr = c(1,2,3,4,5,6,7),
                           Date = c(rep("2022-09-30", 2),
                                    "2022-10-14",
                                    "2022-10-28",
                                    "2022-11-04",
                                    "2022-11-11",
                                    "2022-11-11"),
                           Topic = c(
                             paste0("[One Locus Marker Data](", s_data_url, "p1_mrk_one_locus.csv)", collapse = ""),
                             paste0("[Multiple Loci Marker Data](", s_data_url, "p1_mrk_5_loci.csv)", collapse = ""),
                             paste0("[QTL Data](", s_data_url, "p1_qtl_1_loci.csv)", collapse = ""),
                             paste0("[Weaning weight data](", s_data_url, "beef_data_bc.csv)", collapse = ""),
                             paste0("[Pedigree Example 1](", s_data_url, "ped_ex1.csv)", collapse = ""),
                             paste0("[Pedigree numerator relationship matrix](", s_data_url, "ped_num_rel_mat.csv)", collapse = ""),
                             paste0("[Pedigree from slides](", s_data_url,"ped_sl_rel_mat.csv)", collapse = "")
                           ))
knitr::kable(tbl_data)
```


## Notebooks

```{r, nb-table, echo=FALSE, message=FALSE, warning=FALSE}
s_my_nb_url <- file.path(root_url, "my_nb/")
tbl_nb <- tibble::tibble(Nr = c(1, 2, 3),
                         Date = c("2022-09-30",
                                  "2022-10-07",
                                  "2022-10-07"),
                         Topic = c(
                           paste0("[Quantiative Genetics](", s_my_nb_url, "qg_data_demo.nb.html)", collapse = ""),
                           paste0("[Single Locus Breeding Values](", s_my_nb_url, "20221007_single_locus_bv.nb.html)", collapse = ""),
                           paste0("[Breeding Values From Data](", s_my_nb_url, "qg_estimate_bv.nb.html)", collapse = "")
                         ))
knitr::kable(tbl_nb)
```


```{r, echo=FALSE, results='asis'}
cat(rmdhelp::get_latest_change())
```

