---
title: "Solutions"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Solutions}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Solutions to exercises are listed here.

```{r, echo=FALSE, results='asis'}
s_sol_url <- "https://charlotte-ngs.github.io/lbgfs2022/sol/"
tbl_sol <- tibble::tibble(Nr = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10),
                          Date = c("2022-09-30",
                                  "2022-10-07",
                                  "2022-10-14",
                                  "2022-10-21",
                                  "2022-10-28",
                                  "2022-11-11",
                                  "2022-11-25",
                                  "2022-12-02",
                                  "2022-12-09",
                                  "2022-12-16"),
                          Topic = c(
                           paste0("[Linear Algebra](", s_sol_url, "lbg_ex02_sol.pdf)", collapse = ""),
                           paste0("[Quantitative Genetics](", s_sol_url, "lbg_ex03_sol.pdf)", collapse = ""),
                           paste0("[QTL Data](", s_sol_url, "lbg_ex04_sol.pdf)", collapse = ""),
                           paste0("[Genetic Evaluation](", s_sol_url, "lbg_ex05_sol.pdf)", collapse = ""),
                           paste0("[Fixed linear effects model](", s_sol_url, "lbg_ex06_sol.pdf)", collapse = ""),
                           paste0("[Numerator relationship matrix](", s_sol_url, "lbg_ex07_sol.pdf)", collapse = ""),
                           paste0("[Inverse numerator relationship matrix](", s_sol_url, "lbg_ex08_sol.pdf)", collapse = ""),
                           paste0("[Variance and Inbreeding](", s_sol_url, "lbg_ex09.pdf)", collapse = ""),
                           paste0("[Genomic Breeding Values](", s_sol_url, "lbg_ex10_sol.pdf)", collapse = ""),
                           paste0("[Test Exam](", s_sol_url, "20211217_sol_exam.pdf)", collapse = "")
                          ))
knitr::kable(tbl_sol)
```


```{r latest-change, echo=FALSE, results='asis'}
cat(rmdhelp::get_latest_change())
```
