--- 
title: "Livestock Breeding and Genomics"
author: "Peter von Rohr"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [lbgfs2022.bib]
biblio-style: apalike
link-citations: yes
github-repo: charlotte-ngs/lbgfs2022
description: "These are the lecture notes for the course Livestock Breeding and Genomics. This course is taught during the fall semester 2022 at ETH Zurich."
---

```{r setup-preq, echo=FALSE, results='hide'}
### # required packages from CRAN
vec_reqpkgs_cran <- c("knitr", "rmarkdown", "roxygen2", "bookdown", "caTools", "citr", "devtools", "kableExtra")
vec_instpkgs <- installed.packages()
for (p in vec_reqpkgs_cran){
  if (!p %in% vec_instpkgs)
    install.packages(pkgs = p, repos = "https://cran.rstudio.com")
}

### # required packages from github
list_reqpkgs_github <- list(repo=c("charlotte-ngs"), package = c("rmdhelp"))
for (idx in seq_along(1:length(list_reqpkgs_github$package))){
  p <- list_reqpkgs_github$package[idx]
  if (!p %in% vec_instpkgs)
    devtools::install_github(paste(list_reqpkgs_github$repo[idx], p, sep = "/"))
}
```

```{r knitr-setup, include=FALSE}
knitr::opts_chunk$set(fig.pos = "!ht", out.extra = "")
knitr::knit_hooks$set(hook_convert_odg = rmdhelp::hook_convert_odg)
```


```{r mrtminit, include=FALSE}
mrmt <- rmdhelp::MendeleyExportToolR6$new()
mrmt$set_local_bib_file(ps_local_bib_file = 'lbgfs2022.bib')
mrmt$set_this_rmd_file(ps_this_rmd_file = rmdhelp::get_this_rmd_file())
```

